### ISSUE TITLE
Convert partially uploaded exception to user exception 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sapi-importer#23]
```
{
    "message": "Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException: The file \"hotel_asset.csv\" was only partially uploaded. (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php line 235",
    "context": {
        "exception": {
            "class": "Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException",
            "message": "The file \"****\" was only partially uploaded.",
            "code": 0,
            "file": "/var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php:235"
        }
    },
    "level": 500,
    "level_name": "CRITICAL",
    "channel": "sapi-importer",
    "datetime": {
        "date": "2017-01-30 06:27:10.440669",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "extra": {}
}
```

**Comment by ondrejhlavacek** [comment]
@Halama vrtám se v tom a zatím moc nevím, jak tohle otestovat aniž bych porušil ` Tests are completely independent on backend implementation.`.

**Comment by Halama** [comment]
nějaký jakoby unit test jestli to chceš nějak mocknout?

**Comment by Halama** [comment]
zajimalo by me z jakeho duvodu se to deje, kde se to utne?

**Comment by ondrejhlavacek** [comment]
No jasně, injectnout porušenej `UploadedFile` dokážu přes `Request`, ale poruším tím tu nezávislost no... Ale nenapadá mě, jak to udělat jinak.

**Comment by ondrejhlavacek** [comment]
Jo, to si pamatuju, žes minulej tejden říkal, že fix mi necháš, ale na ty důvody mrkneš :-) Děje se to na jednom projektu jenom, ne?

**Comment by Halama** [comment]
ta se tyka tech integracnich testu, tak tam staci pridat druhou test suite ktere budou unit testy.

**Comment by Halama** [comment]
na jakem projektu se to deje bohuzel nevim https://papertrailapp.com/searches/12360473 
to by chtelo taky dotahnout. Trochu s tim souvisi https://github.com/keboola/sapi-importer/issues/19

**Comment by ondrejhlavacek** [comment]
na 19 pak klidně mrknu, ale nechci to teď motat dokupy

**Comment by ondrejhlavacek** [comment]
```Feb 18 04:14:29 import.keboola.com ecs-ext-Import-1P3X4P0KTF5KE-1-sapi-importer-908ef7b6f1aeba8efd0: {"message":"Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException: The file \"20170217_Customers.csv.gz\" was only partially uploaded. (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php line 235","context":{"exception":{"class":"Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException","message":"The file \"20170217_Customers.csv.gz\" was only partially uploaded.","code":0,"file":"/var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php:235"}},"level":500,"level_name":"CRITICAL","channel":"sapi-importer","datetime":{"date":"2017-02-18 03:14:29.768827","timezone_type":3,"timezone":"UTC"},"extra":[]}
```

**Comment by Halama** [comment]
Ale vrátilo to 400, takže si myslím že to funguje ale zároven to zaloguje jako internal:
![image](https://cloud.githubusercontent.com/assets/903531/23301501/849113d2-fa8a-11e6-903d-9bb2f1d45898.png)

**Comment by Halama** [comment]
je to tím že ta exception nemá `code` a tím pádem jí to zaloguje jako CRITICAL.

**Comment by ondrejhlavacek** [comment]
čumim do toho jak vrána, ale nevidím, kde by se podle `code` určoval loglevel? 
tipuju, že tu chybu budu muset chytit uvnitř a přetavit jí na potomka `HttpException` a tomu dát správnej code?

**Comment by Halama** [comment]
https://github.com/silexphp/Silex/blob/v1.3.5/src/Silex/EventListener/LogListener.php#L109

**Comment by ondrejhlavacek** [comment]
Dik, to je presne ono, udělám to tak...

**Comment by Halama** [comment]
jo tu kontrolu typu exception jsem predtim prehledl a myslel jsem ze je to jenom podle code

**Comment by Halama** [comment]
mergnuto https://github.com/keboola/sapi-importer/pull/26

**Comment by ondrejhlavacek** [comment]
![image](https://cloud.githubusercontent.com/assets/497675/23647288/67e785ac-0315-11e7-8fb7-29904b4ea6de.png)

furt to loguje jako 500 i když api vrací 400

**Comment by Halama** [comment]
ted uz by to snad konecne melo byt fixnuty.
